#!/bin/zsh
# set base path

#export GIT_HOME=/usr/local/git

fpath=(/usr/local/share/zsh-completions $fpath)

export PLOCAL="/Users/twl/Dropbox/Local Personal"
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

# these paths for homebrew installed Go
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/.go

# no /opt/local/bin on OS X so remove
export PATH=${PATH/:\/opt\/local\/bin//}

if (( EUID == 0 )); then
    export PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin
fi
